package com.imola.leetcode.hashtable;

/**
 * @author Heng Yu
 * @date 1/20/20 4:20 PM
 */

/**
 * leetcode 389: Find the Difference
 *
 * description: Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 */

public class FindTheDifference {
    public char solution(String s, String t) {
        if (s == null || s.length() == 0)
            return t.charAt(0);

        int[] alphabet = new int[26];

        char[] charS = s.toCharArray();
        char[] charT = t.toCharArray();

        for (int i = 0; i < charS.length; i++) {
            int indexS = charS[i] - 'a';
            int indexT = charT[i] - 'a';
            ++alphabet[indexS];
            --alphabet[indexT];
        }
        int indexT = charT[charT.length - 1] - 'a';
        --alphabet[indexT];

        char res = 0;
        for (int i = 0; i < alphabet.length; i++) {
            if (alphabet[i] != 0) {
                res = (char) ('a' + i);
                break;
            }
        }
        return res;
    }
}
